export const GET_ADDRESS = "GET_ADDRESS";
export const EDIT_ADDRESS_START = "EDIT_ADDRESS_START";
export const EDIT_ADDRESS_SUCCESS = "EDIT_ADDRESS_SUCCESS";
export const EDIT_ADDRESS_FAILED = "EDIT_ADDRESS_FAILED";
