export const CREATE_INVOICE_START = "CREATE_INVOICE_START";
export const CREATE_INVOICE_FAILED = "CREATE_INVOICE_FAILED";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";

export const GET_INVOICE_START = "GET_INVOICE_START";
export const GET_INVOICE_FAILED = "GET_INVOICE_FAILED";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";

export const ADD_INVOICES_LIST = "ADD_INVOICES_LIST";
