export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_PRODUCT_FAILED = "FETCH_PRODUCT_FAILED";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_LIKE = "UPDATE_PRODUCT_LIKE";
